PandemiaHDP/urls.py
from django.contrib import admin
from django.urls import path
from content import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('disease/', views.disease, name='disease'), #List disease
    path('disease/<int:disease_id>/createcomment/', views.create_diseasecomment, name='create_diseasecomment'),
    path('disease/<int:disease_id>/', views.disease_detail, name='disease_detail'),  # Detalles de un blog específico
    path('disease/create/', views.create_or_update_disease, name='create_disease'),    
    path('disease/<int:disease_id>/update/', views.create_or_update_disease, name='update_disease'),

    path('blog/', views.blog, name='blog'),  # Lista de blogs
    path('blog/hipertension.html/', views.hipertension, name='hipertension'),
    path('blog/colesterol.html/', views.colesterol, name='colesterol'),
    path('blog/artritis.html/', views.artritis, name='artritis'),
    path('blog/renal.html/', views.renal, name='renal'),
    path('blog/cardiaca.html/', views.cardiaca, name='cardiaca'),
    path('blog/alzheimer.html/', views.alzheimer, name='alzheimer'),
    path('blog/cancer.html/', views.cancer, name='cancer'),
    path('blog/asma.html/', views.asma, name='asma'),
    path('blog/diabetes.html/', views.diabetes, name='diabetes'),
    path('blog/vih.html/', views.vih, name='vih'),
    path('blog/EPOC.html/', views.EPOC, name='EPOC'),
    path('blog/epilepsia.html/', views.epilepsia, name='epilepsia'),
    path('logout/', views.signout, name='logout'),
    path('signin/', views.signin, name='signin'),
    # Asegúrate de pasar 'blog_id' como parte de la URL para 'create_comment'
    path('blog/<int:blog_id>/createcomment/', views.create_comment, name='create_comment'),
    path('blog/<int:blog_id>/', views.blog_detail, name='blog_detail'),  # Detalles de un blog específico
    path('blog/create/', views.create_or_update_blog, name='create_blog'),
    path('blog/<int:blog_id>/update/', views.create_or_update_blog, name='update_blog'),

]

content/models.py
from django.db import models
from django.contrib.auth.models import User

class Blog(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=200)
    subtitle = models.CharField(max_length=200)
    content = models.TextField(blank=True)
    content2 = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.title + ' - por ' + self.user.username

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    blog = models.ForeignKey(Blog, on_delete=models.CASCADE, related_name='comments')  # Relación con Blog
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    likes = models.PositiveIntegerField(default=0)

    def __str__(self):
        return f"{self.blog.title} - por {self.user.username}"  # Retorna los primeros 50 caracteres

class Disease(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    image = models.CharField(max_length=200)
    description = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return self.name + ' - por ' + self.user.username
    
class DiseaseComment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    disease = models.ForeignKey(Disease, on_delete=models.CASCADE, related_name='diseasecomments')
    content = models.TextField(blank=True)
    created = models.DateTimeField(auto_now_add=True)
    
    def __str__(self):
        return f"{self.disease.name} - por {self.user.username}" 
    
        

content/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment, Blog, Disease, DiseaseComment

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Agregar comentario...'}),
        }

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['title', 'subtitle', 'content', 'content2']
        
class DiseaseCommentForm(forms.ModelForm):
    class Meta:
        model = DiseaseComment
        fields = ['content']
        widgets = {
            'content': forms.Textarea(attrs={'placeholder': 'Agregar comentario...'}),
        }
                
class DiseaseForm(forms.ModelForm):
    class Meta:
        model = Disease
        fields = ['name', 'image', 'description']
                
class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': 'Nombre'}))
    last_name = forms.CharField(max_length=100, required=True, widget=forms.TextInput(attrs={'placeholder': 'Apellido'}))
    
    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('first_name', 'last_name')

    def save(self, commit=True):
        user = super().save(commit=False)
        user.first_name = self.cleaned_data["first_name"]
        user.last_name = self.cleaned_data["last_name"]
        if commit:
            user.save()
        return user

content/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.forms import UserCreationForm, AuthenticationForm
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib import messages  # Importa esto para enviar mensajes al template
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from .forms import CommentForm, BlogForm, DiseaseForm, DiseaseCommentForm, SignUpForm
from .models import Comment, Blog, Disease, DiseaseComment

# Create your views here.

def home(request):
    return render(request, 'home.html')

def signup(request):
    if request.method == 'GET':
        return render(request, 'signup.html', {'form': SignUpForm()})
    else:
        form = SignUpForm(request.POST)
        if form.is_valid():
            try:
                user = form.save()
                login(request, user)
                return redirect('disease')  # Asegúrate de que 'blog' es el nombre correcto de la URL de redirección deseada
            except IntegrityError as e:
                # Aquí puedes comprobar si el error es específico de un nombre de usuario duplicado o algo más
                error_message = 'El nombre de usuario ya está en uso' if 'UNIQUE constraint' in str(e) else 'Ocurrió un error al crear el usuario'
                return render(request, 'signup.html', {'form': SignUpForm(), 'error': error_message})
        else:
            # En caso de que el formulario no sea válido, se renderiza de nuevo con los errores.
            return render(request, 'signup.html', {'form': form, 'error': form.errors})

def signout(request):
    logout(request)
    return redirect('home')

def signin(request):
    if request.method == 'GET':
        return render(request, 'signin.html', {"form": AuthenticationForm})
    else:
        user = authenticate(
            request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'signin.html', {"form": AuthenticationForm, "error": "Username or password is incorrect."})

        login(request, user)
        return redirect('disease')

@login_required
def create_comment(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)  # Obtiene el blog o devuelve un error 404 si no existe
    if request.method == 'GET':
        return render(request, 'create_comment.html', {
            'form': CommentForm(),
            'blog': blog  # Pasar el blog al contexto puede ser útil para mostrar información en la plantilla
        })
    else:
        try:
            form = CommentForm(request.POST)
            if form.is_valid():
                new_comment = form.save(commit=False)
                new_comment.user = request.user
                new_comment.blog = blog  # Asocia el comentario con el blog
                new_comment.save()
                return redirect('blog_detail', blog_id=blog.id)  # Redirige a la vista detallada del blog
        except ValueError:
            return render(request, 'create_comment.html', {
                'form': CommentForm(),
                'error': 'Error al agregar comentario',
                'blog': blog
            })

def blog(request):
    blogs = Blog.objects.all()  # Obtiene todos los blogs
    return render(request, 'blog.html', {'blogs': blogs})

def blog_detail(request, blog_id):
    blog = get_object_or_404(Blog, pk=blog_id)
    comments = blog.comments.all()  # Utiliza el related_name para obtener todos los comentarios asociados
    return render(request, 'blog_detail.html', {'blog': blog, 'comments': comments})

def es_superusuario(user):
    return user.is_superuser

@login_required
@user_passes_test(es_superusuario)
def create_or_update_blog(request, blog_id=None):
    template_name = 'create_blog.html'  # Plantilla predeterminada para crear un nuevo blog
    
    blog = None
    if blog_id:
        blog = get_object_or_404(Blog, pk=blog_id, user=request.user)  # Asegura que solo el autor pueda editar
        template_name = 'update_blog.html'  # Cambia la plantilla para actualizar un blog existente
    
    if request.method == 'POST':
        form = BlogForm(request.POST, instance=blog)
        try:
            if form.is_valid():
                saved_blog = form.save(commit=False)
                if not blog_id:  # Solo establece el usuario si es un nuevo blog
                    saved_blog.user = request.user
                saved_blog.save()
                return redirect('blog_detail', blog_id=saved_blog.id)
        except ValueError as e:
            # Maneja el error específico aquí. Por ejemplo, podrías enviar un mensaje al template.
            messages.error(request, f'Error al guardar el blog: {e}')
    else:
        form = BlogForm(instance=blog)

    return render(request, template_name, {
        'form': form,
        'blog': blog  # Pasar el blog al contexto puede ser útil
    })
    
@login_required
def create_diseasecomment(request, disease_id):
    disease = get_object_or_404(Disease, pk=disease_id)  # Obtiene el blog o devuelve un error 404 si no existe
    if request.method == 'GET':
        return render(request, 'create_diseasecomment.html', {
            'form': DiseaseCommentForm(),
            'disease': disease  # Pasar el blog al contexto puede ser útil para mostrar información en la plantilla
        })
    else:
        try:
            form = DiseaseCommentForm(request.POST)
            if form.is_valid():
                new_diseasecomment = form.save(commit=False)
                new_diseasecomment.user = request.user
                new_diseasecomment.disease = disease  # Asocia el comentario con el blog
                new_diseasecomment.save()
                return redirect('disease_detail', disease_id=disease.id)  # Redirige a la vista detallada del blog
        except ValueError:
            return render(request, 'create_diseasecomment.html', {
                'form': DiseaseCommentForm(),
                'error': 'Error al agregar enfermedad',
                'disease': disease
            })
                
def disease(request):
    diseases = Disease.objects.all()  # Obtiene todos los blogs
    return render(request, 'disease.html', {'diseases': diseases})

def disease_detail(request, disease_id):
    disease = get_object_or_404(Disease, pk=disease_id)
    diseasecomments = disease.diseasecomments.all()  # Utiliza el related_name para obtener todos los comentarios asociados
    return render(request, 'disease_detail.html', {'disease': disease, 'diseasecomments': diseasecomments})
   
@login_required
@user_passes_test(es_superusuario)
def create_or_update_disease(request, disease_id=None):
    template_name = 'create_disease.html'
    
    disease = None
    if disease_id:
        disease = get_object_or_404(Disease, pk=disease_id, user=request.user)
        template_name = 'update_disease.html'
    
    if request.method == 'POST':
        form = DiseaseForm(request.POST, instance=disease)
        try:
            if form.is_valid():
                saved_disease = form.save(commit=False)
                
                if not disease_id:
                    saved_disease.user =request.user
                saved_disease.save()
                return redirect('disease_detail', disease_id=saved_disease.id)    
        except ValueError as e:
            messages.error(request, f'Error al guardar la enfermedad: {e}')    
    else:
        form = DiseaseForm(instance=disease)
        
    return render(request, template_name, {
        'form': form,
        'disease': disease
    })    
        
    
def hipertension(request):
    return render(request, 'hipertension.html')
def colesterol(request):
    return render(request, 'colesterol.html')
def artritis(request):
    return render(request, 'artritis.html')
def renal(request):
    return render(request, 'renal.html')
def cardiaca(request):
    return render(request, 'cardiaca.html')
def alzheimer(request):
    return render(request, 'alzheimer.html')
def cancer(request):
    return render(request, 'cancer.html')
def asma(request):
    return render(request, 'asma.html')
def diabetes(request):
    return render(request, 'diabetes.html')
def vih(request):
    return render(request, 'vih.html')
def EPOC(request):
    return render(request, 'EPOC.html')
def epilepsia(request):
    return render(request, 'epilepsia.html')

content/templates/EPOC.html
{% extends 'base.html' %}

{% block content %}
<style>
  /* Estilos personalizados */
  h1{
    color: rgb(10, 10, 10); 
    text-shadow: 3px 3px 5px hsl(0, 0%, 43%);
    font-size: 40px; 
    font-weight: bold;
  }
  body{
    background-image: url('/static/media/fondo.jpg');
    background-size: cover; /* Hace que la imagen de fondo cubra todo el cuerpo */
    background-position: center; 
  }
  .apartado p {
    font-size: 1rem;
    text-align: justify;
    text-justify: inter-word;
    margin-top: 10px; /* Añadir un espacio entre el título y el párrafo */
  }
  .enfermedades-container img {
    display: block; /* Permite aplicar márgenes automáticos para centrar */
    margin: auto; /* Centra horizontalmente */
    max-width: 1000%; /* Ajusta la imagen al ancho del contenedor */
    height: auto; /* Mantiene la proporción de aspecto */
    margin-bottom: 20px; /* Agrega un espacio debajo de la imagen */
  }
</style>

<div class="container mt-4">
  <div class="enfermedades-container">
    <h1 class="text-center mb-4">ENFERMEDAD PULMONAR OBSTRUCTIVA CRÓNICA(EPOC)</h1>
        <img src="/static/media/EPOC.jpg" alt="imagen">
        <p>
            La enfermedad pulmonar obstructiva crónica (EPOC) es una enfermedad pulmonar inflamatoria crónica que causa la obstrucción del flujo de aire 
            de los pulmones. Los síntomas incluyen dificultad para respirar, tos, producción de moco (esputo) y sibilancias. Típicamente es causado por 
            la exposición a largo plazo a gases irritantes o partículas de materia, más a menudo por el humo del cigarrillo. Las personas con enfermedad 
            pulmonar obstructiva crónica tienen un mayor riesgo de desarrollar enfermedades cardíacas, cáncer de pulmón y varias otras afecciones.
        </p> 
        <p>
            El enfisema y la bronquitis crónica son las dos afecciones más comunes que contribuyen a la enfermedad pulmonar obstructiva crónica. Estas dos 
            afecciones suelen ocurrir juntas y su gravedad puede variar entre los individuos con enfermedad pulmonar obstructiva crónica.La bronquitis 
            crónica es la inflamación del revestimiento de los bronquios, que llevan el aire hacia y desde los sacos de aire (alvéolos) de los pulmones. 
            Se caracteriza por la tos diaria y la producción de moco (esputo).El enfisema es una afección en la que los alvéolos al final de los pasajes 
            de aire más pequeños (bronquiolos) de los pulmones se destruyen como resultado de una exposición perjudicial al humo de cigarrillo y otros gases 
            y partículas irritantes.
        </p>
        <p>
            Aunque la enfermedad pulmonar obstructiva crónica es una enfermedad progresiva que empeora con el tiempo, es tratable. Con un manejo adecuado, 
            la mayoría de las personas con enfermedad pulmonar obstructiva crónica pueden lograr un buen control de los síntomas y la calidad de vida, así 
            como reducir el riesgo de otras afecciones asociadas.
        </p>
        <p><strong>SÍNTOMAS:</strong></p>
        <p>
            Los síntomas de la enfermedad pulmonar obstructiva crónica no suelen aparecer hasta que se produce un daño pulmonar significativo y suelen empeorar 
            con el tiempo, sobre todo si la exposición al tabaco continúa.
            Los signos y síntomas de la enfermedad pulmonar obstructiva crónica pueden incluir los siguientes:
        </p>
        <p>&bull; Falta de aire, especialmente durante la actividad física</p>
        <p>&bull; Sibilancia</p>
        <p>&bull; Opresión del pecho</p>
        <p>&bull; Una tos crónica que puede producir mucosidad (esputo) que puede ser clara, blanca, amarilla o verdosa</p>
        <p>&bull; Infecciones respiratorias frecuentes</p>
        <p>&bull; Falta de energía</p>
        <p>&bull; Pérdida de peso involuntaria (en etapas posteriores)</p>
        <p>&bull; Hinchazón en tobillos, pies o piernas</p>
        <p>
            También es probable que las personas con enfermedad pulmonar obstructiva crónica experimenten episodios llamados exacerbaciones, durante los cuales 
            sus síntomas empeoran en relación con la variación diaria habitual y persisten por lo menos durante varios días.
        </p>
        <p><strong>CAUSAS:</strong></p>
        <p>
            La principal causa de la EPOC en los países desarrollados es el tabaquismo. En el mundo en desarrollo, la EPOC se produce a menudo en personas expuestas 
            a los gases de la quema de combustible para cocinar y calentar en hogares mal ventilados. Solo algunos fumadores crónicos desarrollan una aparente EPOC, 
            aunque muchos fumadores con largos historiales de tabaquismo pueden desarrollar una función pulmonar reducida. Algunos fumadores desarrollan afecciones 
            pulmonares menos comunes. Pueden ser diagnosticados erróneamente como enfermos de EPOC hasta que se realice una evaluación más completa.
        </p>
        <p><strong>Cómo se ven afectados tus pulmones</strong></p>
        <p>
            El aire viaja por la tráquea y llega a los pulmones a través de dos grandes tubos (bronquios). Dentro de los pulmones, estos tubos se dividen muchas veces, 
            como las ramas de un árbol, en tubos más pequeños (bronquiolos) que terminan en grupos de sacos pequeños de aire (alvéolos).Estos sacos de aire tienen paredes 
            muy delgadas llenas de vasos sanguíneos pequeños (capilares). El oxígeno en el aire que tú inhalas pasa a estos vasos sanguíneos y entra en el torrente sanguíneo. 
            Al mismo tiempo, el dióxido de carbono, gas que es producto del desecho del metabolismo, es exhalado.Tus pulmones dependen de la elasticidad natural de los bronquios 
            y los sacos de aire para forzar la salida del aire de tu cuerpo. La EPOC hace que pierdan su elasticidad y se expandan demasiado, lo que deja algo de aire atrapado en 
            los pulmones al exhalar.
        </p>
        <p><strong>Causas de la obstrucción de las vías respiratorias</strong></p>
        <p>Las causas de la obstrucción de las vías respiratorias incluyen lo siguiente:</p>
        <p>
            &bull; <strong>Enfisema.</strong>Esta enfermedad pulmonar causa la destrucción de las frágiles paredes y fibras elásticas de los alvéolos. Las pequeñas vías respiratorias 
            se colapsan al exhalar, lo que afecta al flujo de aire que sale de los pulmones.
        </p>
        <p>
            &bull; <strong>Bronquitis crónica. </strong>Con esta afección, los bronquios se inflaman y se estrechan y los pulmones producen más moco, lo que puede bloquear aún más los 
            tubos estrechados. Desarrollas una tos crónica para tratar de despejar tus vías respiratorias.
        </p>
        <p><strong>El humo del cigarrillo y otras sustancias irritantes</strong></p>
        <p>
            En la gran mayoría de las personas con enfermedad pulmonar obstructiva crónica, el daño pulmonar que desencadena la enfermedad es consecuencia de haber fumado cigarrillos 
            durante mucho tiempo. Pero es probable que también existan otros factores implicados en el desarrollo de la enfermedad pulmonar obstructiva crónica, como la susceptibilidad 
            genética, porque no todos los fumadores la desarrollan.Otras sustancias irritantes pueden causar enfermedad pulmonar obstructiva crónica, incluidos el humo del cigarro, el 
            humo de segunda mano, el humo de la pipa, la contaminación ambiental y la exposición en el lugar de trabajo a polvo, humo o gases tóxicos.
        </p>
        <p><strong>Deficiencia de alfa-1 antitripsina</strong></p>
        <p>
            En aproximadamente el 1 % de las personas con EPOC, la enfermedad es el resultado de un trastorno genético que causa bajos niveles de una proteína llamada alfa-1 antitripsina 
            (AAt). La proteína AAt se produce en el hígado y se segrega en el torrente sanguíneo para ayudar a proteger los pulmones. La deficiencia de alfa-1 antitripsina puede causar 
            enfermedades hepáticas, pulmonares o ambas. En el caso de los adultos con EPOC relacionada a la deficiencia de AAt, las opciones de tratamiento incluyen las utilizadas para 
            las personas con tipos más comunes de EPOC. Además, algunas personas pueden ser tratadas mediante el reemplazo de la proteína AAt faltante, lo que puede prevenir un mayor daño 
            a los pulmones.
        </p>
        <p><strong>FACTORES DE RIESGO:</strong></p>
        <p> 
            Los factores de riesgo de la enfermedad pulmonar obstructiva crónica incluyen lo siguiente:
        </p>
        <p>
            &bull; <strong>Exposición al humo del tabaco.</strong>El factor de riesgo más significativo para la enfermedad pulmonar obstructiva crónica es el consumo de cigarrillos a largo 
            plazo. Cuanto más años fumes y más paquetes fumes, mayor será el riesgo. Los fumadores de pipa, los fumadores de cigarros y los fumadores de marihuana también pueden estar en riesgo, 
            así como las personas expuestas a grandes cantidades de humo de segunda mano.
        </p>
        <p>
            &bull; <strong>Personas con asma.</strong>El asma, una enfermedad inflamatoria crónica de las vías respiratorias, puede ser un factor de riesgo para desarrollar enfermedad pulmonar 
            obstructiva crónica. La combinación de asma y fumar aumenta el riesgo de enfermedad pulmonar obstructiva crónica incluso más.
        </p>
        <p>
            &bull; <strong>Exposición ocupacional a polvos y sustancias químicas.</strong> La exposición a largo plazo a los gases de sustancias químicas y al polvo en el lugar de trabajo puede 
            irritar e inflamar los pulmones.
        </p>
        <p>
            &bull; <strong>Exposición a los gases de la quema de combustible.</strong>En el mundo en desarrollo, las personas expuestas a los gases de la quema de combustible para cocinar y calentar 
            en hogares mal ventilados corren un mayor riesgo de desarrollar enfermedad pulmonar obstructiva crónica.
        </p>
        <p>
            &bull; <strong>Genética.</strong>El poco común trastorno genético de deficiencia de alfa-1-antitripsina es la causa de algunos casos de enfermedad pulmonar obstructiva crónica. Es probable 
            que otros factores genéticos hagan que ciertos fumadores sean más susceptibles a la enfermedad.
        </p>
        <p><strong>PREVENCIÓN:</strong></p>
        <p>
            A diferencia de algunas enfermedades, la enfermedad pulmonar obstructiva crónica normalmente tiene una causa clara y un camino claro de prevención, y existen maneras de frenar la progresión de 
            la enfermedad. La mayoría de los casos están directamente relacionados con el consumo de cigarrillos, y la mejor manera de prevenir la enfermedad pulmonar obstructiva crónica es no fumar nunca, 
            o dejar de fumar ahora. Si eres fumador desde hace mucho tiempo, estas simples afirmaciones podrían no parecer tan simples, especialmente si ya has tratado de dejar de fumar una, dos o muchas 
            veces antes. Aun así, sigue intentándolo. Es esencial encontrar un programa para dejar el tabaco que pueda ayudarte a abandonar el hábito para siempre. Es tu mejor oportunidad para reducir el 
            daño a tus pulmones.
        </p>
        <p>
            La exposición ocupacional a gases y polvos químicos es otro factor de riesgo para la enfermedad pulmonar obstructiva crónica. Si trabajas con este tipo de irritantes pulmonares, habla con tu 
            supervisor sobre las mejores formas de protegerse, como el uso de equipos de protección respiratoria.
        </p>
        <p>
            A continuación, te damos algunas medidas que puedes tomar para prevenir las complicaciones asociadas con la enfermedad pulmonar obstructiva crónica:
        </p>
        <p>&bull; Deja de fumar para contribuir a reducir el riesgo de tener enfermedades cardíacas y cáncer de pulmón.</p>
        <p>&bull; Aplícate la vacuna antigripal todos los años y la vacuna contra la neumonía neumocócica regularmente para reducir el riesgo o prevenir algunas infecciones.</p>
  </div><p>&bull; Habla con tu médico si te sientes triste o impotente, o si piensas que puedes estar experimentando una depresión.</p>
</div>
</div>
{% endblock %}

content/templates/blog_detail.html
{% extends 'base.html' %}
{% block content %}
<div class="container mt-4">
  <!-- Detalles del Blog -->
  <div class="mb-4">
    <h1 class="display-4">{{ blog.title }}</h1> <!-- Título del Blog -->
    <p>{{ blog.content }}</p> <!-- Contenido -->
    <h2>{{ blog.subtitle }}</h2> <!-- Subtítulo -->
    <p>{{ blog.content2 }}</p> <!-- Contenido 2 -->
    <p class="text-muted text-end">Publicado el {{ blog.created|date:"d/m/Y" }} por {{ blog.user.username }}</p> <!-- Fecha de creación y autor, alineado a la derecha -->
  </div>

  <!-- Comentarios -->
  <div class="card">
    <div class="card-header">
      <h4 class="card-title">Comentarios:</h4> <!-- Tamaño de título ajustado -->
    </div>
    <ul class="list-group list-group-flush">
      {% for comment in comments %}
        <li class="list-group-item">
          <h6 class="mb-1"><strong>{{ comment.user.username }}</strong> dijo:</h6> <!-- Tamaño de título ajustado -->
          <p class="mb-1">{{ comment.content }}</p>
          <small class="text-muted">Likes: {{ comment.likes }}</small>
          <small class="text-muted d-block">Comentado el {{ comment.created|date:"d/m/Y H:i" }}</small>
        </li>
      {% empty %}
        <li class="list-group-item">No hay comentarios aún.</li>
      {% endfor %}
    </ul>
  </div>

  <!-- Botón para añadir comentarios -->
  <div class="d-flex justify-content-end mt-3">
    <a href="{% url 'create_comment' blog.id %}" class="btn btn-primary">Añadir comentario</a>
  </div>
</div>
{% endblock %}

content/templates/create_disease.html
{% extends 'base.html' %}
{% load widget_tweaks %}

{% block content %}
<div class="container mt-4">
  <h1>Crear una nueva enfermedad</h1>
  <!-- Muestra errores del formulario si los hay -->
  {% if error %}
    <div class="alert alert-danger" role="alert">
      {{ error }}
    </div>
  {% endif %}
  
  <!-- Formulario para crear un nuevo blog -->
  <form method="post">
    {% csrf_token %}
    <div class="form-group mb-3">
      <label for="id_title">Nombre de la enfermedad:</label>
      {{ form.name|add_class:"form-control" }}
    </div>
    <div class="form-group mb-3">
      <label for="id_content">Descripcion de enfermedad:</label>
      {{ form.description|add_class:"form-control" }}
    </div>
    <div class="form-group mb-3">
      <label for="id_subtitle">Imagen:</label>
      {{ form.image|add_class:"form-control" }}
    </div>
    <button type="submit" class="btn btn-primary">Publicar Enfermedad</button>
  </form>
</div>
{% endblock %}